### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by wemersonjanuario** [triggerdesign/Hermes#1]
Can't install on laravel 5 project. Your 2.\* tag doesn't require aproprieated illuminate/support.

Could you fix it?

**Comment by schneider-simon** [comment]
Thank you for reporting this issue.
I will take a look at it this week.

**Comment by schneider-simon** [comment]
Hermes 2.1 is now ready for Laravel 5.1
Please perform a composer update and take a look at the new installation procedure in the readme file.

**Comment by wemersonjanuario** [comment]
Ok, Thanks, I will try.
Please update README.md  and instruct users publish migration only for your provider 
php artisan vendor:publish --provider="Triggerdesign\Hermes\HermesServiceProvider"

Thanks
